### ISSUE TITLE
Getting hasConsented when user clicks dismiss

### ISSUE THREAD

**Issue by mdawart** [osano/cookieconsent#450] opened 2018-08-29 13:17 UTC
I am using the script with "type": "opt-in" but getting this.hasConsented() true even if the user clicks the dismiss button?

**Comment by relicmelex** [comment] 2019-07-21 19:18
@mdawart Sorry for the delayed response. Are you still experiencing this? If so can you please reply with some more information like follows so we're better able to reproduce your issue.

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.

**Comment by relicmelex** [comment] 2019-07-25 20:48
@iamwebrocker & @mdawart 

Agreed!

Because we already have #452 open and I've linked that in the documentation issue #568 I'm closing this one with these references.

**Closed by relicmelex** 2019-07-25 20:48 UTC
Labels: awaiting reply
